---
editor_options: 
  markdown: 
    wrap: 72
---
# Locally Selected, Nationally Recognized High School Academic Assessments

## 7.1 State Procedures for the Use of Locally Selected, Nationally Recognized High School Academic Assessments
Evidence to support this portion of the critical element for the selected assessment may include:
• Evaluations of the degree to which the nationally recognized academic assessments align with State content standards. This evidence may also have been used in submissions for critical elements 2.1, 2.2, 3.1, and 3.2.

Collectively, evidence to support this portion of the critical element for the selected assessment includes documentation that the State plans to have in place procedures that ensure that districts administer the selected assessment to all high school students in the district (except for students who are assessed with an AA-AAAS). This evidence may include:
• Proposed documents for districts on the use of the selected assessment.
• Proposed monitoring procedures and tools that the State has in place to ensure that districts assess all students with the selected assessment (e.g., State reports of district participation for tested grades for the selected assessment).
Evidence to support this portion of the critical element for the selected assessment may include:
• Documentation that the nationally recognized academic assessments provide testing accommodations that permit students with disabilities and English learners the opportunity to participate in each assessment and receive equal benefits.
• A description of any technical criteria considered that address the evaluation of equal benefits for students with disabilities or ELs who participate in the selected assessment.
• Evidence of a completed review (e.g., internal report, independent panel review, TAC recommendations/reviews) that documents the application of the equal benefits criteria to the selected assessment.

## 7.2 State Monitoring of Districts Regarding the Use of Locally Selected, Nationally Recognized High School Academic Assessments
Collectively, evidence to support this critical element for the selected assessment documents that the State has in place a procedure that ensures that districts administer the selected assessment to all students in the district (except for students who are assessed with an AA-AAAS). This evidence may include:
• Informative documents for districts on the use of the selected assessment;
• Application materials and guidance provided to districts by the State that outline the procedures for requesting and maintaining approval to use the selected assessment;
• Samples of assurances received from districts regarding the use of the selected assessment that demonstrate that districts have met all (intent, notification, consultation) requirements prior to their request for permission to use the selected assessment;
• Adopted updated monitoring protocols that will be used by the State when monitoring districts regarding the use of the selected assessment on an annual basis;
• Procedures to annually notify districts regarding the use of State approved nationally recognized high school academic assessment in lieu of the State assessment.
• Samples of letters districts provided to parents regarding the use of State approved nationally recognized high school tests.
• Samples of LEA notifications to State.

## 7.3 Comparability of the Locally Selected Nationally Recognized High School Academic Assessments with the State Assessments
Evidence to support this critical element for the selected assessment may include:
• Empirical analyses that provide evidence regarding the rigor and quality of the selected assessment (e.g., technical reports);
• Studies, research, and analyses to determine the extent to which the nationally recognized academic assessments provide comparable, valid, and reliable data on student achievement as compared to the State high school academic assessments for all students and for each subgroup of students.
• Analyses to determine whether the nationally recognized academic assessments provide unbiased, rational, and consistent differentiation among schools within the State’s accountability system.
• Summaries of reviews conducted by the State to establish the comparability of the selected assessment content coverage, difficulty, and overall quality, especially in contrast to the State assessment;
• Empirical analysis which shows the comparison of student academic achievement data for all high school students and each subgroup of high school students produced by the selected assessment at each academic achievement level with the State assessment; and
• Samples of reports that demonstrate the results for the selected assessment are expressed in terms consistent with the State’s academic achievement standards.
